const V={};
/* Design previews for screens whose backend is not built yet (queue, tables, CRM, offers, staff, social, ads, traffic, WhatsApp, reports).
   All numbers here are made up. */
V.home_sample=()=>{const d=days(range),rev=d.reduce((a,b)=>a+b.rev,0),ad=d.reduce((a,b)=>a+b.ad,0),ord=d.reduce((a,b)=>a+b.ord,0);const t=d[d.length-1];
return head("Tuesday · Hyderabadi Irani","Good evening, Hotel Admin",act("Open POS",1)+act("Add post"),true)+
`<div class="grid g4">${kpi("Revenue · today",INR(t.rev),"▲ 12% vs last Tue",1,d.map(x=>x.rev))}${kpi("Live orders","27",t.ord+" today · 7 waiting",false)}${kpi("Ad spend → sales",(rev/ad).toFixed(1)+"x",INR(ad)+" spent in "+range+"d",1,d.map(x=>x.rev/x.ad))}${kpi("New customers","86","41 from Instagram & WhatsApp",1)}</div>
<div class="grid g21" style="margin-top:14px"><div class="card"><div class="row sb"><div><h3>Sales and ad spend</h3><div class="sub">Last ${range} days · includes tax</div></div><div class="row sub"><span class="pill p-ok">Sales</span><span class="pill p-warn">Ads</span></div></div>${line([{d:d.map(x=>x.rev),c:"var(--lime)"},{d:d.map(x=>x.ad*4),c:"var(--warn)"}],{label:"Sales and ad spend"})}<div class="sub">Ad line drawn at 4x scale so both fit.</div></div>
<div class="card live"><div class="row sb"><h3>Right now</h3>${pill("Live","ok")}</div><div class="grid g3" style="margin:12px 0"><div class="card kpi" style="padding:12px"><small>New</small><strong>7</strong></div><div class="card kpi" style="padding:12px"><small>Cooking</small><strong>9</strong></div><div class="card kpi" style="padding:12px"><small>Ready</small><strong>11</strong></div></div><div class="sub">Oldest ticket 14 min · Queue 6 groups · 9 of 18 tables busy</div><div class="row" style="margin-top:12px"><button class="btn sm" data-go="kds">Kitchen</button><button class="btn sm" data-go="q">Queue</button></div></div></div>
<div class="grid g3" style="margin-top:14px"><div class="card"><h3>Where orders come from</h3><div class="sub">Share of ${ord} orders</div>${bars([["Walk-in",42,chb("web")],["Website",23,chb("web")],["Instagram",15,chb("ig")],["WhatsApp",11,chb("wa")],["Google",9,chb("gg")]],v=>v+"%")}</div>
<div class="card"><h3>Needs attention</h3><div class="sub">Sorted by money at risk</div><div style="display:grid;gap:10px;margin-top:10px">${[["bad","14 WhatsApp chats unanswered","wa"],["warn","Google ads 82% of budget used, 9 days left","ads"],["warn","Biryani stock low, 6 portions","menu"],["info","Instagram token expires in 6 days","con"]].map(a=>`<button class="btn" style="justify-content:flex-start;text-align:left" data-go="${a[2]}">${pill("","" +a[0])}${a[1]}</button>`).join("")}</div></div>
<div class="ai"><b>Nova AI</b><h3 style="margin:8px 0">Friday reel is your best ad</h3><p class="sub" style="margin:0 0 12px">The Dum Biryani reel brought 38 orders for ${INR(920)}. Boosting it for 3 more days could add about ${INR(14000)} in sales.</p><button class="btn pri sm" data-sample>Boost for ₹800</button> <button class="btn sm" data-go="soc">See post</button></div></div>`};
V.q=()=>head("Service","Queue",act("Add walk-in",1),true)+`<div class="grid g3"><div class="card kpi"><small>Waiting</small><strong>6 groups</strong><span class="sub">20 guests</span></div><div class="card kpi"><small>Estimated wait</small><strong>18 min</strong><span class="sub">Based on 9 busy tables</span></div><div class="card kpi"><small>Joined by QR or WhatsApp</small><strong>4 of 6</strong><span class="sub">They get a message when called</span></div></div><div class="card" style="margin-top:14px">${tbl([["Token"],["Name"],["Party",1],["Waiting",1],["Joined via"],[""]],[["A-14","Kiran B","4","22 min","WhatsApp",`<button class="btn sm pri" data-sample>Call now</button>`],["A-15","Sana M","2","17 min","QR",`<button class="btn sm" data-sample>Call</button>`],["A-16","Farhan A","6","12 min","Staff",`<button class="btn sm" data-sample>Call</button>`],["A-17","Divya R","3","8 min","QR",`<button class="btn sm" data-sample>Call</button>`]])}</div>`;
V.tab=()=>{const st=["occ","free","free","occ","pay","free","occ","occ","free","occ","free","occ","pay","free","occ","free","free","occ"];const lb={occ:"Eating",free:"Free",pay:"Paying"};
return head("Service","Tables & QR",act("Print all QR codes",1))+`<div class="chips" style="margin-bottom:14px">${pill("9 eating","warn")}${pill("7 free","ok")}${pill("2 paying","info")}</div><div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(110px,1fr))">${st.map((s,i)=>`<button class="tbl ${s}" data-sample><b>T-${String(i+1).padStart(2,"0")}</b><span class="sub">${lb[s]}</span><span class="mono sub">QR</span></button>`).join("")}</div>`};
const CUS=[["Lakshmi P","Instagram",3680,12,"Regular"],["Imran Q","WhatsApp",3490,9,"Regular"],["Ravi T","Google",3230,7,"New"],["Kiran B","Walk-in",3110,15,"VIP"],["Anil K","Website",2960,4,"New"],["Farhan A","Instagram",2880,11,"Regular"]];
V.cus=()=>head("Business","Customer CRM",act("Export")+act("Message segment",1))+`<div class="grid g4">${kpi("Customers","2,184","▲ 86 this ${range}d".replace("${range}",range),1)}${kpi("Repeat rate","41%","▲ 3 pts",1)}${kpi("Avg lifetime value","₹1,268","▲ ₹84",1)}${kpi("Lapsed 30d+","312","Win-back ready",false)}</div><div class="chips" style="margin:14px 0">${["All","VIP","Regular","New","Lapsed"].map((c,i)=>`<button class="chip" aria-pressed="${i==0}">${c}</button>`).join("")}</div><div class="card">${tbl([["Customer"],["Came from"],["Spend",1],["Orders",1],["Segment"],[""]],CUS.map(c=>[c[0],`<span class="row">${chb(c[1]=="Instagram"?"ig":c[1]=="WhatsApp"?"wa":c[1]=="Google"?"gg":"web")}${c[1]}</span>`,INR(c[2]),c[3],pill(c[4],c[4]=="VIP"?"warn":c[4]=="New"?"info":"ok"),`<button class="btn sm" data-sample>WhatsApp</button>`]))}</div>`;
let OFF=[["Weekend biryani combo","Fri to Sun · 10% off",1,214,41800],["Chai + snack at 4 pm","Daily 4 to 6 pm",1,388,19400],["First order ₹100 off","New customers",1,96,28800],["Lapsed 30 day win-back","WhatsApp, auto-sent",0,0,0]];
V.off=()=>head("Business","Offers engine",act("New offer",1))+`<div class="ai" style="margin-bottom:14px"><b>Nova AI suggestion</b><p style="margin:8px 0 12px">Tuesday lunch is 38% slower than other weekdays. A ₹49 chai add-on to lunch orders could lift it. Send it to customers who ordered in the last 30 days.</p><button class="btn pri sm" data-sample>Create offer</button></div><div class="grid g2">${OFF.map((o,i)=>`<div class="card"><div class="row sb"><h3>${o[0]}</h3>${sw(!!o[2],"off"+i)}</div><div class="sub">${o[1]}</div><div class="grid g2" style="margin-top:14px"><div><small class="sub">Redeemed</small><div class="mono" style="font-size:20px">${o[3]}</div></div><div><small class="sub">Sales from it</small><div class="mono" style="font-size:20px">${INR(o[4])}</div></div></div></div>`).join("")}</div>`;

V.stf=()=>head("Business","Staff",act("Add staff",1))+`<div class="grid g3">${[["Hotel Admin","Owner","All access",1],["Ravi","Cashier","POS, Orders",1],["Suresh","Chef","Kitchen screen",1],["Irfan","Rider","Delivery app",1],["Meena","Captain","Tables, Queue",0],["Asha","Marketing","Social, Ads",1]].map(s=>`<div class="card"><div class="row"><span class="mark" style="width:38px;height:38px;border-radius:50%">${s[0][0]}</span><div><b>${s[0]}</b><div class="sub">${s[1]}</div></div><div class="sp"></div>${pill(s[3]?"On shift":"Off","" +(s[3]?"ok":"mute"))}</div><div class="sub" style="margin-top:12px">Can open: ${s[2]}</div></div>`).join("")}</div>`;
V.soc=()=>head("Growth","Social",act("Connect account")+act("Schedule post",1))+`<div class="grid g4">${[["ig","Instagram","12.4k","▲ 312 this week"],["fb","Facebook","8.1k","▲ 96"],["yt","YouTube","3.2k","▲ 41"],["gg","Google profile","4.7★","1,208 reviews"]].map(a=>`<div class="card"><div class="row">${chb(a[0])}<b>${a[1]}</b></div><div class="mono" style="font-size:22px;margin:10px 0 2px">${a[2]}</div><div class="delta up">${a[3]}</div></div>`).join("")}</div>
<div class="card" style="margin-top:14px"><h3>This week</h3><div class="sub" style="margin-bottom:10px">Scheduled and published posts</div><div class="cal">${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((d,i)=>`<div><em>${d}</em>${[["ig","Chai reel"],0,["fb","Offer card"],["ig","Story poll"],["ig","Biryani reel"],["yt","Kitchen tour"],["gg","Weekend update"]][i]?`<span class="row">${chb([["ig"],0,["fb"],["ig"],["ig"],["yt"],["gg"]][i][0])}</span><div style="margin-top:6px">${[["ig","Chai reel"],0,["fb","Offer card"],["ig","Story poll"],["ig","Biryani reel"],["yt","Kitchen tour"],["gg","Weekend update"]][i][1]}</div>`:`<span class="sub">Nothing planned</span>`}</div>`).join("")}</div></div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Top posts by orders</h3>${tbl([["Post"],["Reach",1],["Orders",1]],[["Dum Biryani reel","48.2k","38"],["Irani chai story","9.1k","14"],["Weekend combo card","6.4k","11"]])}</div><div class="card"><h3>Inbox</h3><div class="sub">Comments and DMs from all accounts</div><div style="display:grid;gap:10px;margin-top:10px">${[["ig","Is the biryani halal and available for 20 people?","2 min"],["fb","Do you deliver to Gachibowli?","18 min"],["gg","Review: 5★ Best chai in Secunderabad","1 h"]].map(m=>`<div class="row">${chb(m[0])}<div style="flex:1;min-width:0">${m[1]}</div><span class="sub">${m[2]}</span><button class="btn sm" data-sample>Reply</button></div>`).join("")}</div></div></div>`;
V.ads=()=>{const d=days(range);const sp=d.map(x=>x.ad);return head("Growth","Ads & spend",act("Connect ad account")+act("New campaign",1))+`<div class="grid g4">${kpi("Ad spend",INR(sp.reduce((a,b)=>a+b)),"▲ 6% vs previous",false,sp)}${kpi("Sales from ads",INR(d.reduce((a,b)=>a+b.rev,0)*.31),"31% of all sales",1)}${kpi("Cost per order","₹46","▼ ₹5 better",1)}${kpi("Return on ad spend","6.8x","▲ 0.4x",1)}</div>
<div class="grid g21" style="margin-top:14px"><div class="card"><h3>Daily spend</h3><div class="sub">All platforms</div>${line([{d:sp,c:"var(--warn)"}],{label:"Daily ad spend"})}</div><div class="card"><h3>Budget pacing</h3><div class="sub">Month so far</div>${[["Meta (Instagram, Facebook)",64,"₹16,000"],["Google Ads",82,"₹10,000"],["YouTube",31,"₹5,000"]].map(b=>`<div style="margin:14px 0"><div class="row sb"><span>${b[0]}</span><span class="mono">${b[1]}% of ${b[2]}</span></div><div class="bar" style="margin-top:6px"><i style="width:${b[1]}%;${b[1]>80?"background:var(--warn)":""}"></i></div></div>`).join("")}</div></div>
<div class="card" style="margin-top:14px"><h3>Campaigns</h3>${tbl([["Campaign"],["Platform"],["Spend",1],["Clicks",1],["Orders",1],["Return",1],["Status"]],[["Biryani weekend reel","Instagram","₹6,200","3,410","138","7.9x",pill("Winning","ok")],["Near me: biryani","Google","₹8,200","2,180","94","5.4x",pill("Budget 82%","warn")],["Chai happy hour","Facebook","₹3,100","1,420","41","4.1x",pill("Learning","info")],["Kitchen tour","YouTube","₹1,550","890","6","1.2x",pill("Pause?","bad")]])}</div>`};
V.trf=()=>{const hm=Array.from({length:7},(_,r)=>`<span>${["M","T","W","T","F","S","S"][r]}</span>`+Array.from({length:24},(_,h)=>{const v=Math.max(0,Math.min(1,(rnd(r+1,h)*.5+(h>=11&&h<=14?.5:0)+(h>=19&&h<=22?.6:0)+(r>=4?.15:0))-.15));return`<i title="${Math.round(v*100)} visits" style="opacity:${.08+v*.92}"></i>`}).join("")).join("");
return head("Growth","Traffic",act("Share link tracking")+act("Export"))+`<div class="grid g4">${kpi("Visits","18,420","▲ 14%",1)}${kpi("Menu views","11,260","61% of visits",1)}${kpi("Started checkout","1,940","10.5%",1)}${kpi("Paid orders","1,132","6.1% conversion",1)}</div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Where visitors come from</h3><div class="sub">Tracked links and QR codes</div>${bars([["Instagram bio and stories",5120,chb("ig")],["Google search and Maps",4640,chb("gg")],["WhatsApp links",3380,chb("wa")],["Table and poster QR",2910,chb("web")],["Facebook",1460,chb("fb")],["YouTube",910,chb("yt")]],v=>v.toLocaleString("en-IN"))}</div>
<div class="card"><h3>Funnel</h3><div class="sub">Visit to paid order</div>${[["Visited",18420],["Viewed menu",11260],["Added to cart",3870],["Started checkout",1940],["Paid",1132]].map((f,i)=>`<div style="margin:12px 0"><div class="row sb"><span>${f[0]}</span><span class="mono">${f[1].toLocaleString("en-IN")}</span></div><div class="bar" style="margin-top:5px"><i style="width:${f[1]/184.2}%"></i></div></div>`).join("")}</div></div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Busy hours</h3><div class="sub" style="margin-bottom:10px">Visits by weekday and hour</div><div class="heat">${hm}</div></div><div class="card"><h3>Areas and devices</h3>${bars([["Secunderabad",38],["Begumpet",22],["Gachibowli",14],["Kukatpally",11]],v=>v+"%")}<div class="sub" style="margin-top:12px">Phone 87% · Desktop 11% · Tablet 2%</div></div></div>`};
V.wa=()=>head("Growth","WhatsApp",act("New broadcast",1),true)+`<div class="grid g4">${kpi("Conversations","1,284","▲ 9%",1)}${kpi("Orders via WhatsApp","214","₹86,400 sales",1)}${kpi("First reply time","2m 40s","Goal under 3m",1)}${kpi("Unanswered","14","Oldest 26 min",false)}</div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Automations</h3><div class="sub">Messages we send for you</div><div style="display:grid;gap:14px;margin-top:14px">${[["Order confirmation and tracking link",1],["Ready for pickup",1],["Abandoned cart after 30 min",1],["Reorder reminder after 14 days",0],["Ask for a Google review",1],["Table booking confirmation",1]].map((a,i)=>`<div class="row sb"><span>${a[0]}</span>${sw(!!a[1],"a"+i)}</div>`).join("")}</div></div>
<div class="card"><h3>Live chat</h3><div class="sub" style="margin-bottom:12px">Imran Q · customer since Mar 2026</div><div class="msg in">Is 20 plate biryani possible for tomorrow 8 pm?</div><div class="msg out">Yes. We can have it ready by 7:30 pm. Pay ₹10,400 here to confirm.</div><div class="msg in">Sending now</div><div class="row" style="margin-top:12px"><button class="btn sm" data-sample>Send payment link</button><button class="btn sm" data-sample>Add to catering</button></div></div></div>
<div class="card" style="margin-top:14px"><h3>Broadcasts</h3>${tbl([["Message"],["Audience",1],["Delivered",1],["Read",1],["Orders",1]],[["Weekend biryani combo","1,820","1,790","1,214","46"],["Chai happy hour","940","931","702","21"],["We reopened after Diwali","2,100","2,060","1,480","58"]])}</div>`;
V.rep=()=>head("Growth","Reports",act("Schedule delivery",1))+`<div class="grid g3">${[["Monthly growth report","September 2026","Sales, ad spend, social reach, traffic and WhatsApp in one summary"],["Ad spend report","September 2026","Spend, return and cost per order by platform"],["GST statement","September 2026","Taxable value and GST by day, ready for your accountant"],["Day-end report","Today","Sales by payment type and channel"],["Customer and loyalty","Last 90 days","New, repeat and lapsed customers"],["Staff and kitchen speed","Last 14 days","Average cook time and late tickets"]].map(r=>`<div class="card"><h3>${r[0]}</h3><div class="sub">${r[1]}</div><p class="sub" style="min-height:44px">${r[2]}</p><div class="row"><button class="btn sm pri" data-sample>View</button><button class="btn sm" data-sample>Send to WhatsApp</button><button class="btn sm" data-sample>Email</button></div></div>`).join("")}</div><div class="card" style="margin-top:14px"><div class="row sb"><div><h3>Send the monthly report automatically</h3><div class="sub">On the 1st of every month, 9:00 am, to the owner's WhatsApp and email</div></div>${sw(true,"rp")}</div></div>`;
let CON=[["ig","Instagram","@hyderabadi.irani","ok","Posts, reach, comments"],["fb","Facebook","Hyderabadi Irani page","ok","Posts, ads, inbox"],["gg","Google Business and Ads","2 locations","warn","Reviews, search, ad spend"],["yt","YouTube","Hyderabadi Irani Kitchen","ok","Videos, views"],["wa","WhatsApp Business","+91 98••• ••210","ok","Chats, broadcasts, orders"],["web","Website tracking","hyderabadiirani.net","ok","Visits, sources, checkout"]];
V.con=()=>head("Setup","Connections")+`<p class="sub" style="max-width:62ch;margin:0 0 16px">Connect each account once. We only read what is listed under each one, plus the actions you switch on. You can disconnect any time.</p><div class="grid g2">${CON.map((c,i)=>`<div class="card"><div class="row">${chb(c[0])}<div style="flex:1;min-width:0"><b>${c[1]}</b><div class="sub">${c[2]}</div></div>${pill(c[3]=="ok"?"Connected":c[3]=="warn"?"Reconnect in 6 days":"Not connected",c[3]=="ok"?"ok":c[3]=="warn"?"warn":"mute")}</div><div class="sub" style="margin:12px 0">We use: ${c[4]}</div><button class="btn sm ${c[3]=="ok"?"":"pri"}" data-con="${i}">${c[3]=="ok"?"Disconnect":"Connect"}</button></div>`).join("")}</div>`;
