const V={};
/* Design previews for screens whose backend is not built yet (queue, social, ads, traffic, WhatsApp, reports, connections).
   All numbers here are made up. */
V.q=()=>head("Service","Queue",act("Add walk-in",1),true)+`<div class="grid g3"><div class="card kpi"><small>Waiting</small><strong>6 groups</strong><span class="sub">20 guests</span></div><div class="card kpi"><small>Estimated wait</small><strong>18 min</strong><span class="sub">Based on 9 busy tables</span></div><div class="card kpi"><small>Joined by QR or WhatsApp</small><strong>4 of 6</strong><span class="sub">They get a message when called</span></div></div><div class="card" style="margin-top:14px">${tbl([["Token"],["Name"],["Party",1],["Waiting",1],["Joined via"],[""]],[["A-14","Kiran B","4","22 min","WhatsApp",`<button class="btn sm pri" data-sample>Call now</button>`],["A-15","Sana M","2","17 min","QR",`<button class="btn sm" data-sample>Call</button>`],["A-16","Farhan A","6","12 min","Staff",`<button class="btn sm" data-sample>Call</button>`],["A-17","Divya R","3","8 min","QR",`<button class="btn sm" data-sample>Call</button>`]])}</div>`;

V.soc=()=>head("Growth","Social",act("Connect account")+act("Schedule post",1))+`<div class="grid g4">${[["ig","Instagram","12.4k","▲ 312 this week"],["fb","Facebook","8.1k","▲ 96"],["yt","YouTube","3.2k","▲ 41"],["gg","Google profile","4.7★","1,208 reviews"]].map(a=>`<div class="card"><div class="row">${chb(a[0])}<b>${a[1]}</b></div><div class="mono" style="font-size:22px;margin:10px 0 2px">${a[2]}</div><div class="delta up">${a[3]}</div></div>`).join("")}</div>
<div class="card" style="margin-top:14px"><h3>This week</h3><div class="sub" style="margin-bottom:10px">Scheduled and published posts</div><div class="cal">${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((d,i)=>`<div><em>${d}</em>${[["ig","Chai reel"],0,["fb","Offer card"],["ig","Story poll"],["ig","Biryani reel"],["yt","Kitchen tour"],["gg","Weekend update"]][i]?`<span class="row">${chb([["ig"],0,["fb"],["ig"],["ig"],["yt"],["gg"]][i][0])}</span><div style="margin-top:6px">${[["ig","Chai reel"],0,["fb","Offer card"],["ig","Story poll"],["ig","Biryani reel"],["yt","Kitchen tour"],["gg","Weekend update"]][i][1]}</div>`:`<span class="sub">Nothing planned</span>`}</div>`).join("")}</div></div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Top posts by orders</h3>${tbl([["Post"],["Reach",1],["Orders",1]],[["Dum Biryani reel","48.2k","38"],["Irani chai story","9.1k","14"],["Weekend combo card","6.4k","11"]])}</div><div class="card"><h3>Inbox</h3><div class="sub">Comments and DMs from all accounts</div><div style="display:grid;gap:10px;margin-top:10px">${[["ig","Is the biryani halal and available for 20 people?","2 min"],["fb","Do you deliver to Gachibowli?","18 min"],["gg","Review: 5★ Best chai in Secunderabad","1 h"]].map(m=>`<div class="row">${chb(m[0])}<div style="flex:1;min-width:0">${m[1]}</div><span class="sub">${m[2]}</span><button class="btn sm" data-sample>Reply</button></div>`).join("")}</div></div></div>`;
V.ads=()=>{const d=days(range);const sp=d.map(x=>x.ad);return head("Growth","Ads & spend",act("Connect ad account")+act("New campaign",1))+`<div class="grid g4">${kpi("Ad spend",INR(sp.reduce((a,b)=>a+b)),"▲ 6% vs previous",false,sp)}${kpi("Sales from ads",INR(d.reduce((a,b)=>a+b.rev,0)*.31),"31% of all sales",1)}${kpi("Cost per order","₹46","▼ ₹5 better",1)}${kpi("Return on ad spend","6.8x","▲ 0.4x",1)}</div>
<div class="grid g21" style="margin-top:14px"><div class="card"><h3>Daily spend</h3><div class="sub">All platforms</div>${line([{d:sp,c:"var(--warn)"}],{label:"Daily ad spend"})}</div><div class="card"><h3>Budget pacing</h3><div class="sub">Month so far</div>${[["Meta (Instagram, Facebook)",64,"₹16,000"],["Google Ads",82,"₹10,000"],["YouTube",31,"₹5,000"]].map(b=>`<div style="margin:14px 0"><div class="row sb"><span>${b[0]}</span><span class="mono">${b[1]}% of ${b[2]}</span></div><div class="bar" style="margin-top:6px"><i style="width:${b[1]}%;${b[1]>80?"background:var(--warn)":""}"></i></div></div>`).join("")}</div></div>
<div class="card" style="margin-top:14px"><h3>Campaigns</h3>${tbl([["Campaign"],["Platform"],["Spend",1],["Clicks",1],["Orders",1],["Return",1],["Status"]],[["Biryani weekend reel","Instagram","₹6,200","3,410","138","7.9x",pill("Winning","ok")],["Near me: biryani","Google","₹8,200","2,180","94","5.4x",pill("Budget 82%","warn")],["Chai happy hour","Facebook","₹3,100","1,420","41","4.1x",pill("Learning","info")],["Kitchen tour","YouTube","₹1,550","890","6","1.2x",pill("Pause?","bad")]])}</div>`};
V.trf=()=>{const hm=Array.from({length:7},(_,r)=>`<span>${["M","T","W","T","F","S","S"][r]}</span>`+Array.from({length:24},(_,h)=>{const v=Math.max(0,Math.min(1,(rnd(r+1,h)*.5+(h>=11&&h<=14?.5:0)+(h>=19&&h<=22?.6:0)+(r>=4?.15:0))-.15));return`<i title="${Math.round(v*100)} visits" style="opacity:${.08+v*.92}"></i>`}).join("")).join("");
return head("Growth","Traffic",act("Share link tracking")+act("Export"))+`<div class="grid g4">${kpi("Visits","18,420","▲ 14%",1)}${kpi("Menu views","11,260","61% of visits",1)}${kpi("Started checkout","1,940","10.5%",1)}${kpi("Paid orders","1,132","6.1% conversion",1)}</div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Where visitors come from</h3><div class="sub">Tracked links and QR codes</div>${bars([["Instagram bio and stories",5120,chb("ig")],["Google search and Maps",4640,chb("gg")],["WhatsApp links",3380,chb("wa")],["Table and poster QR",2910,chb("web")],["Facebook",1460,chb("fb")],["YouTube",910,chb("yt")]],v=>v.toLocaleString("en-IN"))}</div>
<div class="card"><h3>Funnel</h3><div class="sub">Visit to paid order</div>${[["Visited",18420],["Viewed menu",11260],["Added to cart",3870],["Started checkout",1940],["Paid",1132]].map((f,i)=>`<div style="margin:12px 0"><div class="row sb"><span>${f[0]}</span><span class="mono">${f[1].toLocaleString("en-IN")}</span></div><div class="bar" style="margin-top:5px"><i style="width:${f[1]/184.2}%"></i></div></div>`).join("")}</div></div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Busy hours</h3><div class="sub" style="margin-bottom:10px">Visits by weekday and hour</div><div class="heat">${hm}</div></div><div class="card"><h3>Areas and devices</h3>${bars([["Secunderabad",38],["Begumpet",22],["Gachibowli",14],["Kukatpally",11]],v=>v+"%")}<div class="sub" style="margin-top:12px">Phone 87% · Desktop 11% · Tablet 2%</div></div></div>`};
V.wa=()=>head("Growth","WhatsApp",act("New broadcast",1),true)+`<div class="grid g4">${kpi("Conversations","1,284","▲ 9%",1)}${kpi("Orders via WhatsApp","214","₹86,400 sales",1)}${kpi("First reply time","2m 40s","Goal under 3m",1)}${kpi("Unanswered","14","Oldest 26 min",false)}</div>
<div class="grid g2" style="margin-top:14px"><div class="card"><h3>Automations</h3><div class="sub">Messages we send for you</div><div style="display:grid;gap:14px;margin-top:14px">${[["Order confirmation and tracking link",1],["Ready for pickup",1],["Abandoned cart after 30 min",1],["Reorder reminder after 14 days",0],["Ask for a Google review",1],["Table booking confirmation",1]].map((a,i)=>`<div class="row sb"><span>${a[0]}</span>${sw(!!a[1],"a"+i)}</div>`).join("")}</div></div>
<div class="card"><h3>Live chat</h3><div class="sub" style="margin-bottom:12px">Imran Q · customer since Mar 2026</div><div class="msg in">Is 20 plate biryani possible for tomorrow 8 pm?</div><div class="msg out">Yes. We can have it ready by 7:30 pm. Pay ₹10,400 here to confirm.</div><div class="msg in">Sending now</div><div class="row" style="margin-top:12px"><button class="btn sm" data-sample>Send payment link</button><button class="btn sm" data-sample>Add to catering</button></div></div></div>
<div class="card" style="margin-top:14px"><h3>Broadcasts</h3>${tbl([["Message"],["Audience",1],["Delivered",1],["Read",1],["Orders",1]],[["Weekend biryani combo","1,820","1,790","1,214","46"],["Chai happy hour","940","931","702","21"],["We reopened after Diwali","2,100","2,060","1,480","58"]])}</div>`;
V.rep=()=>head("Growth","Reports",act("Schedule delivery",1))+`<div class="grid g3">${[["Monthly growth report","September 2026","Sales, ad spend, social reach, traffic and WhatsApp in one summary"],["Ad spend report","September 2026","Spend, return and cost per order by platform"],["GST statement","September 2026","Taxable value and GST by day, ready for your accountant"],["Day-end report","Today","Sales by payment type and channel"],["Customer and loyalty","Last 90 days","New, repeat and lapsed customers"],["Staff and kitchen speed","Last 14 days","Average cook time and late tickets"]].map(r=>`<div class="card"><h3>${r[0]}</h3><div class="sub">${r[1]}</div><p class="sub" style="min-height:44px">${r[2]}</p><div class="row"><button class="btn sm pri" data-sample>View</button><button class="btn sm" data-sample>Send to WhatsApp</button><button class="btn sm" data-sample>Email</button></div></div>`).join("")}</div><div class="card" style="margin-top:14px"><div class="row sb"><div><h3>Send the monthly report automatically</h3><div class="sub">On the 1st of every month, 9:00 am, to the owner's WhatsApp and email</div></div>${sw(true,"rp")}</div></div>`;
let CON=[["ig","Instagram","@hyderabadi.irani","ok","Posts, reach, comments"],["fb","Facebook","Hyderabadi Irani page","ok","Posts, ads, inbox"],["gg","Google Business and Ads","2 locations","warn","Reviews, search, ad spend"],["yt","YouTube","Hyderabadi Irani Kitchen","ok","Videos, views"],["wa","WhatsApp Business","+91 98••• ••210","ok","Chats, broadcasts, orders"],["web","Website tracking","hyderabadiirani.net","ok","Visits, sources, checkout"]];
V.con=()=>head("Setup","Connections")+`<p class="sub" style="max-width:62ch;margin:0 0 16px">Connect each account once. We only read what is listed under each one, plus the actions you switch on. You can disconnect any time.</p><div class="grid g2">${CON.map((c,i)=>`<div class="card"><div class="row">${chb(c[0])}<div style="flex:1;min-width:0"><b>${c[1]}</b><div class="sub">${c[2]}</div></div>${pill(c[3]=="ok"?"Connected":c[3]=="warn"?"Reconnect in 6 days":"Not connected",c[3]=="ok"?"ok":c[3]=="warn"?"warn":"mute")}</div><div class="sub" style="margin:12px 0">We use: ${c[4]}</div><button class="btn sm ${c[3]=="ok"?"":"pri"}" data-con="${i}">${c[3]=="ok"?"Disconnect":"Connect"}</button></div>`).join("")}</div>`;
